version: '3.8'

services:
  betteredge-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betteredge-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - betteredge-network

networks:
  betteredge-network:
    driver: bridge

